name: Generate data

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workpath: ./questionnaires

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ env.workpath }}
    
    - name: Checkout old dist
      uses: actions/checkout@v2
      with:
        ref: 'generated'
        path: questionnaires/dist

    - name: Generate data
      run: python main.py
      working-directory: ${{ env.workpath }}

    - name: Push generated data
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: generated
        repository: questionnaires/dist
        commit_options: '--allow-empty'
        commit_message: |
          update generated data

          Triggered by $GITHUB_SHA
